# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdt_token', models.CharField(max_length=250)),
                ('paypal_email', models.EmailField(max_length=254)),
                ('return_url', models.URLField()),
                ('paypal_url', models.URLField()),
                ('pdt_url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchaser',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='resource',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
