# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppsDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iOsTitulo', models.CharField(max_length=250)),
                ('iOsDescripcion', models.CharField(max_length=250)),
                ('androidTitulo', models.CharField(max_length=250)),
                ('androidDescripcion', models.CharField(max_length=250)),
            ],
        ),
    ]
